export {
  currentYear,
  deepCopy,
  isNullOrUndefined,
  getYears,
  timeoutAction,
  sleep,
  logOnDev,
  convertToRGBA,
  detectDeviceTypeAndOS,
  scrollToTop,
  scrollToTopNoneSmooth,
  generateRandomNumber,
  setScreenSize,
  transformArrayToDictByKey,
  openPhoneApp,
  openSmsApp,
  openKakaoMap,
  openTMap,
  openNaverMap,
  copyToClipboard,
} from './common-lib.ts';
